package event;
// Generated 20-Apr-2020 13:32:11 by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String email;
     private String pass;
     private String name;

    public Users() {
    }

    public Users(String email, String pass, String name) {
       this.email = email;
       this.pass = pass;
       this.name = name;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


